### ISSUE TITLE
CW0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai181-gorban#14]
Це контрольне питання ви отримали під час проведення Code Review вашого рішення на завдання лабораторної роботи № 0 (вступної), розпочатого вами після створення запиту Pull Request.
Правильну відповідь на запитання дозволять вам отримати додаткові 2 бали до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Вілповідь вкажіть у вигляді коментаря.

Запитання:
Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес аутентифікації через пароль на процес з використанням Token під час безпечного оновлення GitHub-репозиторію. Поясніть, будь ласка, чому так було зроблено?

**Comment by alexandergorban** [comment]
@oleksandrblazhko Доброго дня, так звісно, дякую!
Це було зроблено по тій причині що використання токенів має ряд переваг:
1. Аутентифікація на основі токенів більш масштабована та ефективна так як токени зберігаються на стороні користувача, вони пропонують масштабоване рішення. Більше того, серверу просто потрібно створити та перевірити токени разом із інформацією, що означає, що обслуговування більшої кількості користувачів на веб-сайті чи в додатку можливо без будь-яких проблем.
2. Гнучкість і продуктивність. Це є іншими важливими аспектами, коли йдеться про автентифікацію на основі маркерів, оскільки їх можна використовувати на кількох серверах і вони можуть запропонувати автентифікацію для різноманітних веб-сайтів і програм одночасно. Тобто один і той токен можна виrористовувати для GitHub, GitLab, Bitbucket і так далі.
Це допомагає заохочувати більше можливостей співпраці між різними сервісами та программами.
3. Токени пропонують надійну безпеку
Оскільки маркери, такі як токени, не мають стану, лише секретний ключ може перевірити його, коли він отриманий програмою на стороні сервера, яка використовувалася для його створення. Тому вони вважаються найкращим і найбезпечнішим способом автентифікації. Токени діють як сховище для облікових даних користувача, і коли токен переміщається між сервером або веб-браузером, збережені облікові дані ніколи не скомпрометовані.

Тобто дане введення дає більше переваг та розширяє можливості використання сервісів.

**Comment by oleksandrblazhko** [comment]
Оцінка = 2 бали.
Посилання на інші КП - https://drive.google.com/drive/u/1/folders/1UVrJ8n0EfDcbMHni6Isg9I7UY275--_Y

**Comment by alexandergorban** [comment]
@oleksandrblazhko дякую!
